# Borrowed from https://github.com/TanayB11/me/blob/main/.github/workflows/deploy.yaml
# Executes on push
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          # TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}